<Project>
  <PropertyGroup>
    <Authors>Michael Ciccotti</Authors>
    <Version>0.7.4</Version>
    <Copyright>Copyright (c) 2026 Michael Ciccotti</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/mydogisbox/Walkthrough</PackageProjectUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>
</Project>
